ministryofjustice/ds-auth

db/migrate/20150325173027_remove_permission_id_fields.rb

In order for `remove_column` to be reversible the type needs to be supplied.

Make RemovePermissionIdFields migration reversible

---

README.md
bin/render_api
public/api.html

Added a script to render the API docs in an HTML format
Renders apiary.apib file to a HTML document into public/api.html that can then be viewed in browser
Requires npm and [aglio](https://github.com/danielgtaylor/aglio)
Think this is a better way of having a visual way of view the API docs than using apiary.io

Render api docs

---

db/migrate/20150330085857_enable_uuid_ossp_extension.rb
db/migrate/20150330090025_add_uid_to_users.rb

* This adds an `uid` field to each User, relying on Postgres to
insert an auto-generated uuid on record save

Add uid to User

---

config/initializers/doorkeeper.rb

As all our User accounts are pre-defined and it is a closed system we do not need to authorize each app
https://www.pivotaltracker.com/story/show/89525174

always autoapprove consuming apps

---

.env.development
.env.test
config/database.yml

Setting the db name in .env causes only the creation of the
development database, since rake tasks such as `db:create` are ran by
default in development environment.
This has the consequence of not respecting setup rake tasks,
reproducible by running `rake db:create:all` and noticing the output of
"<db name> development already exists>" in triplicate (one per env).
.env files have also been updated to reflect the change.

Set test database name in database yml

---

app/controllers/api/v1/api_controller.rb
app/controllers/api/v1/credentials_controller.rb
app/models/null_profile.rb
app/serializers/credentials_serializer.rb
config/routes.rb
db/schema.rb
spec/factories/doorkeeper_factories.rb
spec/factories/government_application.rb
spec/factories/permission.rb
spec/factories/user.rb
spec/requests/api/v1/credentials/show_spec.rb
spec/serializers/credentials_serializer_spec.rb
spec/support/response_json.rb

After the Oauth procedure, we want to return a payload of data that
contains several points of info regarding the user.
This PR sets an `/api/v1/me` route, pointing to
`Api::V1::CredentialsController#show`, returning the required
information.

Add User credentials endpoint

---

app/models/null_profile.rb
app/serializers/credentials_serializer.rb
db/migrate/20150413131301_move_uid_from_users_to_profiles.rb
db/schema.rb
spec/factories/profile.rb
spec/factories/user.rb
spec/requests/api/v1/credentials/show_spec.rb
spec/serializers/credentials_serializer_spec.rb

https://www.pivotaltracker.com/story/show/92326100
* This is in order to switch to using the UIDs as params for the API instead of DB IDs.

Move UID from the User to the Profile model

---

app/serializers/profile_serializer.rb
spec/requests/api/v1/profiles/index_spec.rb
spec/requests/api/v1/profiles/show_spec.rb
spec/serializers/profile_serializer_spec.rb
spec/serializers/profiles_serializer_spec.rb

* Switch Profile API endpoints to expose the Organisation UIDs rather than the database IDs, for consistency across the entire API

Organisation UIDs on API

---

app/serializers/credentials_serializer.rb
spec/factories/profile.rb
spec/requests/api/v1/credentials/show_spec.rb
spec/serializers/credentials_serializer_spec.rb

* No longer expose organisation_ids, instead expose organisation_uids
* Implements: https://www.pivotaltracker.com/story/show/92603170

Expose organisation_uids on credentials /me endpoint

---

drs-auth_client/lib/drs/auth_client/client.rb
drs-auth_client/spec/lib/drs/auth_client/client_spec.rb

* Pass optional `options` hash to `organisations` and `profiles` methods and append them as query params

Allow options to be passed to profiles and organisations endpoints

---

app/controllers/doorkeeper/authorizations_with_role_check_controller.rb
config/routes.rb
spec/requests/doorkeeper/authorization_spec.rb

Check that user has a role for the application they are logging into before issuing an oauth code to the consuming application
Will redirect the user to the auth/failure url on the consuming app (assumes ```/auth/failure``` https://github.com/intridea/omniauth/blob/master/lib/omniauth/failure_endpoint.rb)
Finishes https://www.pivotaltracker.com/story/show/89526616
**Don't merge until the below pull requests have been merged:**
* https://github.com/ministryofjustice/defence-request-service/pull/143
* https://github.com/ministryofjustice/defence-request-service-rota/pull/35

Don't issue oauth token for unauthorised users

---

db/seeds/organisations.rb
db/seeds/roles-permissions.rb
db/seeds/users.rb

No apps implement the admin role, so there is no need for it. 
We also need to specify *some* role for users logging in to the rota app or their authentication will fail.

Remove admin user and add laa users in seeds

---

app/controllers/permissions_controller.rb
app/models/permission.rb
app/views/organisations/show.html.erb
app/views/permissions/index.html.erb
spec/features/permission_management_spec.rb

Allows the removal of permissions for a user from the same view where they can be added on the Organisation show page:

Remove permission from Organisation detail page

---

app/models/organisation.rb
db/seeds/applications.rb
db/seeds/organisations.rb
db/seeds/roles-permissions.rb
db/seeds/users.rb
spec/features/organisation_management_spec.rb

Currently seed failures generate no error output, which makes failed environment builds difficult to detect.
We now raise errors if a seed fails to save
**NOTES**
Please check my changes in app/models/organisation.rb - which makes https://github.com/ministryofjustice/defence-request-service-auth/blob/master/db/seeds/organisations.rb#L24 work.
Please note that I've *not* made similar changes to https://github.com/ministryofjustice/defence-request-service-auth/blob/master/db/seeds/roles-permissions.rb#L10-L33 because these cause errors on a re-run. That probably needs fixing too

[make_seed_failures_raise_errors] Make seed failures raise errors

---

.dockerignore
.gitignore
Makefile

* Integrated /.git-revision file which contains info on the SHA when the build was run

[jenkins_builds] Changing Builds to run on Jenkins instead of CircleCI

---

docker/Dockerfile-development
docker/Dockerfile-test

Upgraded to phantomJS 1.9.8 so that Jasmine doesn't download an updated version. Fixes #94491484
URL for PhantomJS: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2

[install_phantomjs_1_9_8] Install 1.9.8

---

Makefile
app/controllers/status_controller.rb
config/routes.rb
lib/ping_response.rb
spec/controllers/status_controller_spec.rb
spec/lib/ping_response_spec.rb

As per https://github.com/ministryofjustice/defence-request-service/pull/179
Cleaned up some old cases of writing .git-revision file - which is replaced with /.version.yml

[add_ping_response] Add status controller for pings

---

drs-auth_client/lib/drs/auth_client/client.rb

When passed an empty array of uids or organisations to retrieve, the AuthAPI was returning all of the entries for organisations.
This is due to a request being formed with a filtering key (uid or type) but the value pointing to an empty array. Since requests of this type have the key stripped out, there is no way to correctly distinguish them
from a properly formed request to list all of the organisations. In `Api::V1::OrganisationsController#find_organisations`, we always return a scope of records in order to support lookup operations. With no distinction between correctly formed and incorrectly formed requests, the API would return the full list of records.
This PR addresses the issue by implementing a short-circuiting method in the client gem, stopping any incorrectly formed requests …

Stop AuthAPI returning all results incorrectly

---

config/settings.yml

The ERB code would place the string true/false in the YAML. When the YAML is
then parsed, the true/false is evaluated as an actual true/false, rather than a
string containing "true" or "false".
We thus do not need to check the string equivalent value in the yaml

[clean_up_true_false_yaml_handling] Simplified true/false handling in Yaml

---

app/serializers/credentials_serializer.rb
spec/factories/doorkeeper_application.rb
spec/requests/api/v1/credentials/show_spec.rb
spec/serializers/credentials_serializer_spec.rb

Requesting `/api/v1/me` now returns more details about each organisation and does not return global roles any more.

Include organisations in credentials call

---

app/controllers/application_controller.rb

All other pages are protected by auth, this means
after logging out and hitting the homepage
(default redirect), you will be given a flash
message telling you to login in before continuing.
By redirecting straight to the sign in page, there
is no subsequent redirect and we can have a nice
"Signed out successfully" message

Redirect to sign in page after logout

---

.env.development
.env.test
config/settings.yml

Make projects consistent - AWS_REGION env var so that it can be used by Shoryuken and S3 asset_sync

[add_aws_region_env_var] Add AWS_REGION env variable

---

.example.env
Gemfile
Gemfile.lock
README.md
app/controllers/api/v1/api_controller.rb
app/helpers/application_helper.rb
app/models/user.rb
config/initializers/devise.rb
config/initializers/doorkeeper.rb
config/settings.yml
spec/factories/user.rb
spec/features/users_session_timing_out_spec.rb
spec/requests/api/v1/credentials/show_spec.rb
spec/requests/api/v1/organisations/index_spec.rb
spec/requests/api/v1/organisations/show_spec.rb
spec/requests/api/v1/users/index_spec.rb
spec/requests/api/v1/users/show_spec.rb
spec/support/request_helpers.rb

* default timeout period to 1 hour
* use the same timeout value for doorkeeper and devise so when doorkeeper responds with a 401 and the user is redirected to devise to login the devise session has also expired

enable session timeouts for doorkeeper and devise

---

README.md
docker-compose.yml
docker/Dockerfile-development

Introduced a data-only container to allow the postgres data volume to persist across container restarts.
Also removed the explicit "db:reset" call every time the web container starts.

Make the development database persistent

---

spec/rails_helper.rb

This fixes an issue with the environment set up when trying to run individual tests via rspec, rather than test suites via rake
It was not auto-loading the DatabaseCleaner dependency, causing a message 'undefined constant DatabaseCleaner' after the test.
Fixed by explicitly requiring it in rails_helper.rb

Allow specs to be run with rspec executable
