Gemfile
Gemfile.lock
config/initializers/doorkeeper.rb
config/locales/doorkeeper.en.yml
config/routes.rb
db/migrate/20150316103749_create_doorkeeper_tables.rb
db/schema.rb

- setup doorkeeper to play nice with devise
https://www.pivotaltracker.com/story/show/89525174

Setup Doorkeeper

---

apiary.apib

Initial rundown of internal API that the Auth App will expose
Uses API blueprint spec:
* http://apiary.io/blueprint
* https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md

Add api docs for internal api

---

.gitignore
config/unicorn.rb
deploy/after_push
deploy/before_restart
deploy/restart

* As per 26b0e6c39181eb34ee128e65f126056c95cd2660 in defence-request-service repo.
* Changed the order of items in gitignore so that the directory tmp/ exists, even if the
files in it are ignored.

[git_deploy] Integrated git-deploy to match defence-request-service

---

app/controllers/organisations_controller.rb
app/views/organisations/_form.html.erb
app/views/organisations/index.html.erb
app/views/organisations/show.html.erb
spec/features/organisation_management_spec.rb

We weren't exposing all the attributes that should be editable on organisations, only the required ones.

Fix organisation CRUD interface

---

db/migrate/20150330093105_remove_permission_id_from_government_application.rb
db/migrate/20150330093505_add_time_stamps_to_government_applications.rb
db/migrate/20150330093516_add_time_stamps_to_memberships.rb
db/migrate/20150330093528_add_time_stamps_to_permissions.rb
db/migrate/20150330093538_add_time_stamps_to_profiles.rb
db/migrate/20150330093546_add_time_stamps_to_roles.rb
db/migrate/20150330094216_add_time_stamps_to_organisations.rb
db/schema.rb

- add timestamps to all tables
- remove permissions_id from government_applications
https://www.pivotaltracker.com/story/show/89526250

Add and remove columns

---

.env.development
.env.test
config/application.rb
config/settings.yml

* Unifies configs with other projects
* Added sections and comments to .env.development and .env.test
* Enabled enable_starttls_auto on email, since it should always be true
* Changed ordering and layout of settings.yml to match other projects, so it's easier to compare across projects
* Changed double-quoted strings to single-quoted strings

[configure_smtp_server] Correctly configure smtp server

---

deploy/after_push
deploy/slack_notification

Posts a message like below into the moj-dsds slack room after every deploy (aka git push) to staging
/cc @oskarpearson you ok with hard coding variables in here? Is is worth using ENV?

Post notification in slack room after deploying

---

app/controllers/api/v1/api_controller.rb
app/controllers/api/v1/credentials_controller.rb
app/serializers/credentials_serializer.rb
config/routes.rb
spec/serializers/credentials_serializer_spec.rb

* Changes serializers to respond to to_json
* Defaults API to respond with json

Refactor serializers

---

apiary.apib
public/api.html

* Use UIDs instead of IDs to identify profiles and organisations
* Remove redundant `/users` endpoints
* Move `/me` endpoint to be nested under `/profiles`

Update API docs

---

db/migrate/20150415105911_add_uid_to_organisations.rb
db/migrate/20150415131825_add_index_on_uid_on_organisations.rb
db/schema.rb
spec/factories/organisation.rb

* Adds a UID field to the Organisation model and factory
* Will be exposed on the organisation endpoints instead of using standard DB ID fields

Add UID field to Organisation

---

lib/faker/role.rb
spec/mailers/sandbox_email_interceptor_spec.rb

* Test `SandboxEmailInterceptor`
* Remove unused `Faker::Role` method

100% Coverage

---

.env.development
db/seeds/roles-permissions.rb

Enable lookup of applications via `Doorkeeper::Application`

Modify seeds to enable roles across apps

---

app/controllers/organisations_controller.rb
app/helpers/organisations_helper.rb
app/models/organisation.rb
app/views/organisations/_form.html.erb
app/views/organisations/show.html.erb
db/migrate/20150421140404_add_parent_organisation_id_to_organisation.rb
db/schema.rb
spec/features/organisation_management_spec.rb
spec/models/organisation_spec.rb

* Adds `parent_organisation_id` to `Organisation` model
* Ensures that a loop cannot be created in associations

Nested Organisations

---

app/helpers/organisations_helper.rb
app/models/organisation.rb
app/views/organisations/_form.html.erb
app/views/organisations/show.html.erb
config/locales/en.yml
db/migrate/20150424092725_update_old_organisation_type_values.rb
db/schema.rb
db/seeds/organisations.rb
spec/factories/organisation.rb
spec/features/organisation_management_spec.rb
spec/models/organisation_spec.rb

* Convert to using a select box instead of a text field
* Limited to one of four mandatory options

Organisation Type Field

---

app/models/organisation.rb
config/locales/en.yml
spec/features/organisation_management_spec.rb

Pretty much explains itself. :8ball:

Add "court" as an option for organisation_type

---

.gitignore
Makefile
circle.yml
config/database.yml
docker/Dockerfile-base
docker/Dockerfile-production

Gets Docker and circleci configs in-line between the different projects.
Now uses MOJ base container.

[docker_container_repository_92999546] Integrated changes from defence-request-service

---

Rakefile

As per https://github.com/ministryofjustice/defence-request-service/pull/145

[bug/fix_rake_spec_93977974] Integrated fix to "rake spec"

---

.env.test
docker/Dockerfile-development
docker/Dockerfile-test

* Added variables to the .env.test file so that we can run tests in the container
* Added PhantomJS, since it's required in the test container. Matched it's structure
to the other containers

[unified_test_env_config] Integrated changes from .env.development to .env.test

---

app/controllers/sessions_controller.rb
config/routes.rb

https://www.pivotaltracker.com/story/show/93266326

Allow consuming apps to logout

---

app/assets/javascripts/organisations.js
app/assets/stylesheets/application.scss
app/controllers/organisations_controller.rb
app/helpers/organisations_helper.rb
app/models/organisation.rb
app/serializers/organisation_serializer.rb
app/views/organisations/_form.html.erb
app/views/organisations/show.html.erb
config/locales/en.yml
db/migrate/20150518131629_add_details_to_organisations.rb
db/schema.rb
spec/factories/organisation.rb
spec/features/law_firm_organisation_management_spec.rb
spec/features/organisation_management_spec.rb
spec/requests/api/v1/organisations/index_spec.rb
spec/requests/api/v1/organisations/show_spec.rb

https://www.pivotaltracker.com/story/show/91028776
Adds a details field to Organisations which is a hash (jsonb)
Only shows supplier field for law firm type Organisations, not others

Add supplier_number field to law_firm type Organisations

---

drs-auth_client/CHANGELOG.md
drs-auth_client/lib/drs/auth_client/models/organisation.rb
drs-auth_client/lib/drs/auth_client/version.rb

Need it for the new CSO dashboard

Add tel to organisations

---

app/serializers/organisation_serializer.rb
db/seeds/organisations.rb
spec/requests/api/v1/organisations/show_spec.rb

Required to make https://github.com/ministryofjustice/defence-request-service-auth/pull/79 work

Expose tel attribute on Organisations over API

---

app/controllers/dashboard_controller.rb
app/controllers/welcome_controller.rb
app/models/role_loader.rb
app/models/user.rb
app/presenter/dashboard_presenter.rb
app/views/dashboard/index.html.erb
app/views/welcome/index.html.erb
config/locales/en.yml
config/routes.rb
lib/doorkeeper/extensions/application.rb
spec/features/user_logging_in_spec.rb

Puts in a simple dashboard / landing page when users log into the Auth app
* Gives links to the Organisation(s) the User belongs to
* Gives links to the Applications the User has access to

Dashboard links

---

.env.development
.env.test
Gemfile
Gemfile.lock
config/initializers/asset_sync.rb
config/settings.yml

Integrated changes as per https://github.com/ministryofjustice/defence-request-service/pull/205

[assets_on_s3] Store assets on S3

---

app/controllers/api/v1/users_controller.rb
app/models/user.rb
config/routes.rb
spec/requests/api/v1/users/index_spec.rb
spec/requests/api/v1/users/search_spec.rb
spec/requests/api/v1/users/show_spec.rb
spec/serializers/organisation_serializer_spec.rb

* Does what it says on the tin.
* Standard API authorization
* Case insensitive, exact match

Users search API endpoint

---

app/controllers/doorkeeper/authorizations_with_role_check_controller.rb
app/controllers/doorkeeper/custom_applications_controller.rb
app/helpers/doorkeeper_helper.rb
app/views/doorkeeper/applications/_delete_form.html.erb
app/views/doorkeeper/applications/_form.html.erb
app/views/doorkeeper/applications/edit.html.erb
app/views/doorkeeper/applications/index.html.erb
app/views/doorkeeper/applications/new.html.erb
app/views/doorkeeper/applications/show.html.erb
app/views/doorkeeper/authorizations/error.html.erb
app/views/doorkeeper/authorizations/new.html.erb
app/views/doorkeeper/authorizations/show.html.erb
app/views/doorkeeper/authorized_applications/_delete_form.html.erb
app/views/doorkeeper/authorized_applications/index.html.erb
app/views/layouts/doorkeeper/admin.html.erb
app/views/layouts/doorkeeper/application.html.erb
config/locales/doorkeeper.en.yml
config/routes.rb
db/migrate/20150714090556_add_authorized_login_option_to_oauth_applications.rb
db/migrate/20150714105710_rename_only_allow_authorized_login_on_doorkeeper_application.rb
db/schema.rb
spec/factories/doorkeeper_application.rb
spec/requests/doorkeeper/authorization_spec.rb

* Depends on the setting of the `handles_own_authorization` flag when creating/editing an Application

Allow Applications to handle their own authorization

---

config/unicorn.rb

Using adp as a guide: https://github.com/ministryofjustice/advocate-defence-payments/blob/develop/config/unicorn.rb

change unicorn config to match other digital standalone rails apps

---

app/controllers/doorkeeper/authorizations_with_role_check_controller.rb
app/controllers/doorkeeper/custom_applications_controller.rb
app/models/concerns/doorkeeper/custom_application_mixin.rb
app/validators/failure_uri_validator.rb
app/views/doorkeeper/applications/_form.html.erb
app/views/doorkeeper/applications/index.html.erb
app/views/doorkeeper/applications/show.html.erb
config/initializers/doorkeeper.rb
config/locales/doorkeeper.en.yml
db/migrate/20150714125125_add_failure_uri_to_doorkeeper_application.rb
db/schema.rb
spec/requests/doorkeeper/authorization_spec.rb

* Same as the Redirect URI field, except that it has a default value if not provided. Uses same validation

Customise Failure URIs

---

app/assets/javascripts/delete_on_list.js
app/assets/stylesheets/app-elements/layout.scss
app/assets/stylesheets/app-elements/tables.scss
app/views/doorkeeper/applications/index.html.erb
app/views/organisations/index.html.erb
app/views/users/index.html

Use js to show/hide the confirm delete dialog when deleting items on a list view

Enhance list delete
